Fixed TypeError: a bytes-like object is required, not 'int'
Fixed Exception in python3:
  File "BeaconScanner.py", line 19, in <module>
    returnedList = ScanUtility.parse_events(sock, 10)
  File "/home/pi/BLE-Beacon-Scanner/ScanUtility.py", line 107, in parse_events
    rssi, = struct.unpack("b", packet[packetOffset -1])
TypeError: a bytes-like object is required, not 'int'